### ISSUE TITLE
rightscale.server_array.Execute does not handle 403 correctly

### ISSUE THREAD

**Issue by diranged** [Nextdoor/kingpin#232]
When a 403 is returned, we are not handling it correctly and are instead printing out a stack trace. We should handle it and raise an InvalidCredentials exception.

```
12:12:46   DEBUG    37640 [kingpin.utils                           ] [wrapper             ] Exception caught in <function make_generic_request at 0x106458758>((<kingpin.actors.rightscale.api.RightScale object at 0x106457ad0>, u'/api/clouds/6/instances/DBMF6ISEHMJLE/run_executable'), {'post': {u'inputs[COMMAND]': u'text:uptime', u'inputs[USERNAME]': u'text:root', 'right_script_href': u'/api/right_scripts/527606003'}}): 403 Client Error: Forbidden
12:12:46   DEBUG    37640 [kingpin.utils                           ] [wrapper             ] Traceback (most recent call last):
  File "/Users/diranged/git/Nextdoor/dev-tools/kingpin/.venv/lib/python2.7/site-packages/kingpin/utils.py", line 179, in wrapper
    return func(*args, **kwargs)
  File "/Users/diranged/git/Nextdoor/dev-tools/kingpin/.venv/lib/python2.7/site-packages/kingpin/actors/rightscale/api.py", line 682, in make_generic_request
    response = self._client.client.post(url, data=post)
  File "/Users/diranged/git/Nextdoor/dev-tools/kingpin/.venv/lib/python2.7/site-packages/rightscale/httpclient.py", line 90, in request
    r.raise_for_status()
  File "/Users/diranged/git/Nextdoor/dev-tools/kingpin/.venv/lib/python2.7/site-packages/requests/models.py", line 831, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: Forbidden

12:12:46   CRITICAL 37640 [kingpin.actors.rightscale.server_array.Execute] [_execute_array      ] [Puppet Dry Run (env=staging)] Script execution error: Script Execution Error: 403 Client Error: Forbidden
12:12:46   ERROR    37640 [tornado.application                     ] [__del__             ] Future exception was never retrieved: Traceback (most recent call last):
  File "/Users/diranged/git/Nextdoor/dev-tools/kingpin/.venv/lib/python2.7/site-packages/tornado/gen.py", line 606, in callback
    result_list = [i.result() for i in children]
  File "/Users/diranged/git/Nextdoor/dev-tools/kingpin/.venv/lib/python2.7/site-packages/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/Users/diranged/git/Nextdoor/dev-tools/kingpin/.venv/lib/python2.7/site-packages/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/Users/diranged/git/Nextdoor/dev-tools/kingpin/.venv/lib/python2.7/site-packages/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/Users/diranged/git/Nextdoor/dev-tools/kingpin/.venv/lib/python2.7/site-packages/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/diranged/git/Nextdoor/dev-tools/kingpin/.venv/lib/python2.7/site-packages/kingpin/utils.py", line 179, in wrapper
    return func(*args, **kwargs)
  File "/Users/diranged/git/Nextdoor/dev-tools/kingpin/.venv/lib/python2.7/site-packages/kingpin/actors/rightscale/api.py", line 682, in make_generic_request
    response = self._client.client.post(url, data=post)
  File "/Users/diranged/git/Nextdoor/dev-tools/kingpin/.venv/lib/python2.7/site-packages/rightscale/httpclient.py", line 90, in request
    r.raise_for_status()
  File "/Users/diranged/git/Nextdoor/dev-tools/kingpin/.venv/lib/python2.7/site-packages/requests/models.py", line 831, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: Forbidden
```

**Comment by diranged** [comment]
This appears to be related to a behavior change in Tornado 4.1 This is an exception thats being raised outside of the actual method-call we're making. Its raised in this commit (https://github.com/tornadoweb/tornado/commit/241956a6cdd1e96de7afe9355fc3dec303f2365e). This behavior does not happen in Tornado 4.0.

Still digging for the right fix.

**Comment by diranged** [comment]
Until we have a fix, I am going to set the `requirements.txt` to require `tornado>=4.0,<4.1`. I have opened up a bug with the Tornado team looking for help on how to handle this in particular: https://github.com/tornadoweb/tornado/issues/1378
