### ISSUE TITLE
Having trouble creating an MCI with multiple AMI's in a single region.

### ISSUE THREAD

**Issue by nrvale0** [Nextdoor/kingpin#294]
The following script has attempts to map 2 AMI's in us-east-1 and 1 AMI in us-west-1 but fails on the 2nd us-east-1 AMI:

```JSON
{ "actor": "rightscale.mci.Create",
  "desc": "Automagically-built Nextdoor RightScale MCIs",
  "options": {
    "name": "Nextdoor-Ubuntu-14.04-w-RightLink10",
    "description": "Ubuntu 14.04 w/ RightLink10",
    "images": [
	{ "cloud": "ec2 us-east-1", "image": "ami-11f9aa74", "instance_type": "m1.small", "user_data": "cd /bin/bash" },
        { "cloud": "EC2 us-west-1", "image": "ami-b58142f1", "instance_type": "m1.small", "user_data": "cd /bin/bash" },
	{ "cloud": "ec2 us-east-1", "image": "ami-17025072", "instance_type": "m1.small", "user_data": "cd /bin/bash" }
    ]
  }
}
```

Here's a snippet of the error message: 

```ShellSession
2015-10-22 14:16:13,768 DEBUG    61890 [kingpin.utils                           ] [wrapper             ] Exception caught in <function create_resource at 0x105c58848>((<kingpin.actors.rightscale.api.RightScale object at 0x105c71e10>, <rightscale.rightscale.ResourceCollection object at 0x105c71210>, [('multi_cloud_image_setting[cloud_href]', u'/api/clouds/1'), ('multi_cloud_image_setting[image_href]', u'/api/clouds/1/images/FNM6CVAGLCCUK'), ('multi_cloud_image_setting[instance_type_href]', u'/api/clouds/1/instance_types/CQQV62T389R32'), ('multi_cloud_image_setting[user_data]', u'cd /bin/bash')]), {}): 422 Client Error: Unprocessable Entity
2015-10-22 14:16:13,769 DEBUG    61890 [kingpin.utils                           ] [wrapper             ] Traceback (most recent call last):
  File "/Users/nathan/.anyenv/envs/pyenv/versions/2.7.3/lib/python2.7/site-packages/kingpin-0.3.0rc0-py2.7.egg/kingpin/utils.py", line 182, in wrapper
    return func(*args, **kwargs)
  File "/Users/nathan/.anyenv/envs/pyenv/versions/2.7.3/lib/python2.7/site-packages/kingpin-0.3.0rc0-py2.7.egg/kingpin/actors/rightscale/api.py", line 289, in create_resource
    return res.create(params=params)
  File "build/bdist.macosx-10.11-x86_64/egg/rightscale/rightscale.py", line 43, in rsr_meth
    response = self.client.request(http_method, path, **kwargs)
  File "build/bdist.macosx-10.11-x86_64/egg/rightscale/httpclient.py", line 90, in request
    r.raise_for_status()
  File "/Users/nathan/.anyenv/envs/pyenv/versions/2.7.3/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 422 Client Error: Unprocessable Entity```

**Comment by nextdoor-ops-ro** [comment]
You can't set two AMIs for the same region -- thats kind of the point of
the MCI. Howver, we should be able to prevent that in a check in our code.

Matt Wise
Sr. Systems Architect
Nextdoor.com

**Comment by nrvale0** [comment]
Y, I just realized...
